# Generated by Django 3.2.19 on 2023-06-03 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
        migrations.AddField(
            model_name='review',
            name='result',
            field=models.CharField(default='긍정적인 리뷰', max_length=15),
        ),
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0, 100), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
